### ISSUE TITLE
about page build error

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#265]
The about page is improperly using the logger.   
`logger.log()` is not a valid function. We should use `logger.warn()` or `logger.error()` instead.
In the production build logs, this error is thrown.  (for each translation)

``` bash
4:30:03 PM: TypeError: logger.a.log is not a function
4:30:03 PM:     at twitter_TwitterService._fetch (services/twitter.js:42:0)
4:30:03 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
4:30:03 PM:     at async twitter_TwitterService.getTweets (services/twitter.js:87:0)
4:30:03 PM:     at async asyncData (pages/about.vue:45:0)
4:30:03 PM: [error] logger.a.log is not a function
4:30:03 PM:   at twitter_TwitterService._fetch (services/twitter.js:42:0)
4:30:03 PM:   at processTicksAndRejections (node:internal/process/task_queues:96:5)
4:30:03 PM:   at async twitter_TwitterService.getTweets (services/twitter.js:87:0)
4:30:03 PM:   at async asyncData (pages/about.vue:45:0)
4:30:03 PM: [error]  /ms/about
```

**Comment by ermish** [comment]
cc @renderf0x @ann-kilzer @theyokohamalife 

Since our linting is red, this bug was never picked up. We should get it green again! 👍
